name: Compilar APK Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Obtener el código
        uses: actions/checkout@v4

      - name: 2. Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Dar permisos al Gradle Wrapper
        run: chmod +x gradlew

      - name: 4. Compilar el APK de depuración (Debug)
        run: ./gradlew assembleDebug

      - name: 5. Subir el APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: mi-app-android
          path: app/build/outputs/apk/debug/*.apk
